import smtplib
from email.message import EmailMessage
from typing import Dict
from app.core.config import settings, WATCHLIST, SYMBOLS, THRESHOLDS, logger
from app.services.ml_service import predict_signal, load_artifacts
from app.services.history_service import record_signal

_alert_state: Dict[str, dict] = {
    t: {"last_signal": None, "price_alerted": False}
    for t in WATCHLIST
}
_untrained_warned: set = set()
_alert_recipient = None

def get_recipient() -> str:
    return _alert_recipient or settings.EMAIL_USER

def update_recipient(email: str):
    global _alert_recipient
    _alert_recipient = email

def get_alert_state():
    return _alert_state

def reset_alert_state():
    global _alert_state, _untrained_warned
    for ticker in _alert_state:
        _alert_state[ticker] = {"last_signal": None, "price_alerted": False}
    _untrained_warned.clear()
    return list(_alert_state.keys())

def send_email_alert(subject: str, message: str, to_email: str) -> None:
    if not settings.EMAIL_USER or not settings.EMAIL_PASSWORD:
        logger.warning("Email credentials not configured")
        return
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = settings.EMAIL_USER
    msg["To"] = to_email
    msg.set_content(message)
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(settings.EMAIL_USER, settings.EMAIL_PASSWORD)
            smtp.send_message(msg)
        logger.info(f"Email alert sent to {to_email}: {subject}")
    except Exception as e:
        logger.error(f"Email alert failed: {e}")

def check_alerts(ticker_name: str, threshold_price: float, user_email: str) -> None:
    try:
        logger.info(f"Checking alerts for {ticker_name}")
        payload = load_artifacts(ticker_name)

        if payload is None:
            if ticker_name not in _untrained_warned:
                _untrained_warned.add(ticker_name)
                logger.warning(f"No trained model for {ticker_name} — monitoring inactive.")
            return

        result = predict_signal(ticker_name)
        latest_price    = result["price"]
        signal          = result["signal"]
        yf_symbol       = result["yf_symbol"]
        proba           = result["probabilities"]
        confidence_pct  = result.get("confidence_pct", 0.0)
        buy_prob        = result.get("buy_prob", 0.0)
        sell_prob       = result.get("sell_prob", 0.0)
        trend           = result.get("trend", "→")

        # ── Record into signal history ──────────────────────────────────────
        record_signal(
            ticker=ticker_name,
            signal=signal,
            price=latest_price,
            confidence_pct=confidence_pct,
            buy_prob=buy_prob,
            sell_prob=sell_prob,
            trend=trend,
        )

        state = _alert_state.setdefault(ticker_name, {"last_signal": None, "price_alerted": False})

        # Price threshold alert (one-shot until price drops below)
        if latest_price >= threshold_price:
            if not state["price_alerted"]:
                send_email_alert(
                    subject=f"[SignalAI] {ticker_name} Price Alert ₹{latest_price:.0f}",
                    message=(
                        f"⚠️ PRICE ALERT\n\n"
                        f"Stock : {ticker_name} ({yf_symbol})\n"
                        f"Price : ₹{latest_price:.2f}\n"
                        f"Threshold: ₹{threshold_price}\n"
                        f"Signal : {signal} ({confidence_pct:.0f}% confidence)\n"
                    ),
                    to_email=user_email,
                )
                state["price_alerted"] = True
        else:
            state["price_alerted"] = False

        # Signal change alerts
        if signal == state["last_signal"]:
            return

        if signal == "BUY":
            send_email_alert(
                subject=f"[SignalAI] 🟢 BUY Signal — {ticker_name}",
                message=(
                    f"🟢 BUY SIGNAL DETECTED\n\n"
                    f"Stock      : {ticker_name} ({yf_symbol})\n"
                    f"Price      : ₹{latest_price:.2f}\n"
                    f"Confidence : {confidence_pct:.0f}%\n"
                    f"BUY prob   : {buy_prob:.1%}   SELL prob: {sell_prob:.1%}\n"
                    f"Trend      : {trend}\n\n"
                    f"(This is generated by an ML model — not financial advice)"
                ),
                to_email=user_email,
            )
        elif signal == "SELL":
            send_email_alert(
                subject=f"[SignalAI] 🔴 SELL Signal — {ticker_name}",
                message=(
                    f"🔴 SELL SIGNAL DETECTED\n\n"
                    f"Stock      : {ticker_name} ({yf_symbol})\n"
                    f"Price      : ₹{latest_price:.2f}\n"
                    f"Confidence : {confidence_pct:.0f}%\n"
                    f"SELL prob  : {sell_prob:.1%}   BUY prob: {buy_prob:.1%}\n"
                    f"Trend      : {trend}\n\n"
                    f"(This is generated by an ML model — not financial advice)"
                ),
                to_email=user_email,
            )

        state["last_signal"] = signal

    except Exception as e:
        logger.error(f"Alert engine error for {ticker_name}: {e}")

def run_alerts() -> None:
    email = get_recipient()
    if not email:
        logger.warning("No recipient email configured — skipping alert cycle.")
        return
    logger.info("Running alert check...")
    for ticker_name in WATCHLIST:
        try:
            check_alerts(ticker_name, THRESHOLDS.get(ticker_name, 0), email)
        except Exception as e:
            logger.error(f"Alert failed for {ticker_name}: {e}")
